// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: info.proto

#ifndef PROTOBUF_info_2eproto__INCLUDED
#define PROTOBUF_info_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace info {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_info_2eproto();
void protobuf_AssignDesc_info_2eproto();
void protobuf_ShutdownFile_info_2eproto();

class Info;
class Message_t;

// ===================================================================

class Info : public ::google::protobuf::Message {
 public:
  Info();
  virtual ~Info();

  Info(const Info& from);

  inline Info& operator=(const Info& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Info& default_instance();

  void Swap(Info* other);

  // implements Message ----------------------------------------------

  Info* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Info& from);
  void MergeFrom(const Info& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:info.Info)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::google::protobuf::int32 id_;
  friend void  protobuf_AddDesc_info_2eproto();
  friend void protobuf_AssignDesc_info_2eproto();
  friend void protobuf_ShutdownFile_info_2eproto();

  void InitAsDefaultInstance();
  static Info* default_instance_;
};
// -------------------------------------------------------------------

class Message_t : public ::google::protobuf::Message {
 public:
  Message_t();
  virtual ~Message_t();

  Message_t(const Message_t& from);

  inline Message_t& operator=(const Message_t& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message_t& default_instance();

  void Swap(Message_t* other);

  // implements Message ----------------------------------------------

  Message_t* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Message_t& from);
  void MergeFrom(const Message_t& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .info.Info msg = 1;
  inline int msg_size() const;
  inline void clear_msg();
  static const int kMsgFieldNumber = 1;
  inline const ::info::Info& msg(int index) const;
  inline ::info::Info* mutable_msg(int index);
  inline ::info::Info* add_msg();
  inline const ::google::protobuf::RepeatedPtrField< ::info::Info >&
      msg() const;
  inline ::google::protobuf::RepeatedPtrField< ::info::Info >*
      mutable_msg();

  // @@protoc_insertion_point(class_scope:info.Message_t)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::info::Info > msg_;
  friend void  protobuf_AddDesc_info_2eproto();
  friend void protobuf_AssignDesc_info_2eproto();
  friend void protobuf_ShutdownFile_info_2eproto();

  void InitAsDefaultInstance();
  static Message_t* default_instance_;
};
// ===================================================================


// ===================================================================

// Info

// required int32 id = 1;
inline bool Info::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Info::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Info::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Info::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 Info::id() const {
  // @@protoc_insertion_point(field_get:info.Info.id)
  return id_;
}
inline void Info::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:info.Info.id)
}

// required string name = 2;
inline bool Info::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Info::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Info::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Info::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Info::name() const {
  // @@protoc_insertion_point(field_get:info.Info.name)
  return *name_;
}
inline void Info::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:info.Info.name)
}
inline void Info::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:info.Info.name)
}
inline void Info::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:info.Info.name)
}
inline ::std::string* Info::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:info.Info.name)
  return name_;
}
inline ::std::string* Info::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Info::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:info.Info.name)
}

// -------------------------------------------------------------------

// Message_t

// repeated .info.Info msg = 1;
inline int Message_t::msg_size() const {
  return msg_.size();
}
inline void Message_t::clear_msg() {
  msg_.Clear();
}
inline const ::info::Info& Message_t::msg(int index) const {
  // @@protoc_insertion_point(field_get:info.Message_t.msg)
  return msg_.Get(index);
}
inline ::info::Info* Message_t::mutable_msg(int index) {
  // @@protoc_insertion_point(field_mutable:info.Message_t.msg)
  return msg_.Mutable(index);
}
inline ::info::Info* Message_t::add_msg() {
  // @@protoc_insertion_point(field_add:info.Message_t.msg)
  return msg_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::info::Info >&
Message_t::msg() const {
  // @@protoc_insertion_point(field_list:info.Message_t.msg)
  return msg_;
}
inline ::google::protobuf::RepeatedPtrField< ::info::Info >*
Message_t::mutable_msg() {
  // @@protoc_insertion_point(field_mutable_list:info.Message_t.msg)
  return &msg_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace info

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_info_2eproto__INCLUDED
